Repository SRGSSR/pillarbox-apple, pull requests merged in 2023-06, with the labels that each got.

#396 Fix compilation with Xcode 15
  Demo/Sources/Players/BasicPlaybackView.swift
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Players/PlayerLayout.swift
  Demo/Sources/Settings/SettingsView.swift
  Demo/Sources/Settings/UserDefaults.swift
  Demo/Sources/Showcase/TrackingView.swift
  Demo/Sources/Views/CopyButton.swift
  Demo/Sources/Views/SettingsMenu.swift
  Sources/Circumspect/Similarity.swift
  Tests/CoreBusinessTests/MediaMetadataTests.swift
  Tests/PlayerTests/UserInterface/VisibilityTrackerTests.swift
Labels: tooling

#399 Support multiple player instances
  Demo/Sources/Model/Template.swift
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Showcase/MultiView.swift
  Demo/Sources/Showcase/ShowcaseView.swift
  Sources/Player/Player.swift
  docs/GETTING_STARTED.md
  docs/KNOWN_ISSUES.md
Labels: enhancement

#402 Add Apple reference to known issues
  docs/KNOWN_ISSUES.md
Labels: documentation

#400 Add ability to disable AirPlay and Control Center integration
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Sources/Showcase/OptInView.swift
  Demo/Sources/Showcase/ShowcaseView.swift
  Sources/Player/Player.swift
  docs/CONTINUOUS_INTEGRATION.md
  docs/GETTING_STARTED.md
Labels: enhancement

#405 Automatically resume playback when returning from background in specific demos
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Sources/Players/SimplePlayerView.swift
  Demo/Sources/Showcase/BlurredView.swift
  Demo/Sources/Showcase/LinkView.swift
  Demo/Sources/Showcase/Stories/StoriesViewModel.swift
  Demo/Sources/Showcase/TwinsView.swift
  Demo/Sources/Showcase/Wrapped/WrappedView.swift
  Demo/Sources/Tools/Signal.swift
Labels: enhancement

#406 Add the PresentationSize issue with AirPlay among the list of known issues
  docs/KNOWN_ISSUES.md
Labels: documentation

#404 Add showcase demo descriptions
  Demo/Sources/Showcase/ShowcaseView.swift
Labels: enhancement

#409 Fix broken documentation links
  docs/README.md
Labels: documentation

#430 Add system video view overlay support
  Demo/Sources/Router/Router.swift
  Demo/Sources/Views/MessageViews.swift
  Sources/Analytics/ComScore/ComScoreLabels.swift
  Sources/Analytics/CommandersAct/CommandersActLabels.swift
  Sources/Circumspect/Expectations/ExpectAtLeastPublished.swift
  Sources/Circumspect/Expectations/ExpectNothingPublished.swift
  Sources/Circumspect/Expectations/ExpectOnlyPublished.swift
  Sources/Circumspect/Expectations/ExpectPublished.swift
  Sources/Circumspect/Expectations/ExpectResult.swift
  Sources/Circumspect/Matchers.swift
  Sources/Circumspect/Publishers.swift
  Sources/Circumspect/Similarity.swift
  Sources/Core/Publishers.swift
  Sources/Player/Asset.swift
  Sources/Player/ControlCenter/RemoteCommandCenter.swift
  Sources/Player/Publishers/BoundaryTimePublisher.swift
  Sources/Player/Publishers/PeriodicTimePublisher.swift
  Sources/Player/UserInterface/InteractionHostView.swift
  Sources/Player/UserInterface/InteractionView.swift
  Sources/Player/UserInterface/LayoutReader.swift
  Sources/Player/UserInterface/LayoutReaderHost.swift
  Sources/Player/UserInterface/SystemVideoView.swift
  Tests/PlayerTests/Tools/TrackerMock.swift
Labels: enhancement

#433 Remove sentinel
  .swiftpm/xcode/xcshareddata/xcschemes/Analytics.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/Circumspect.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/Core.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/CoreBusiness.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/Diagnostics.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/Pillarbox-Package-NoDebug.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/Pillarbox-Package.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/Player.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/UserInterface.xcscheme
  Demo/Sources/ContentLists/ContentListsView.swift
  Demo/Sources/Settings/SettingsView.swift
  Sources/Player/Internal/QueuePlayer.swift
  Sources/Player/Player.swift
  fastlane/Fastfile
Labels: enhancement

#434 Add some Bitmovin streams
  Demo/Sources/Examples/ExamplesViewModel.swift
  Demo/Sources/Model/Template.swift
Labels: enhancement

#436 Make the project compile again with Xcode 14
  Demo/Sources/Settings/SettingsView.swift
Labels: enhancement
