Repository SRGSSR/pillarbox-apple, pull requests merged in 2023-11, with the labels that each got.

#625 Remove superfluous PiP identifier
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Players/PlayerView.swift
  Demo/Sources/Players/SimplePlayerView.swift
  Demo/Sources/Router/Router.swift
  Demo/Sources/Showcase/MultiView.swift
  Sources/Player/PictureInPicture.swift
  Sources/Player/UserInterface/DidAppearView.swift
  Sources/Player/UserInterface/PictureInPictureButton.swift
  Sources/Player/UserInterface/VideoView.swift
  Sources/Player/UserInterface/View.swift
Labels: enhancement

#630 Restore from Picture in Picture earlier
  Demo/Sources/Router/Router.swift
Labels: enhancement

#638 Improve setting support
  Demo/Resources/Localizable.xcstrings
  Demo/Sources/Players/PlayerConfiguration.swift
  Demo/Sources/Settings/SettingsView.swift
  Demo/Sources/Settings/UserDefaults.swift
  Demo/Sources/Showcase/OptInView.swift
  Sources/Player/Player.swift
  Sources/Player/PlayerConfiguration.swift
  Tests/PlayerTests/Types/PlayerConfigurationTests.swift
Labels: enhancement

#640 Point at matching source code version
  .swiftlint.yml
  Demo/Sources/Showcase/SourceCodeViewable.swift
  Sources/CoreBusiness/Extensions/HTTPURLResponse.swift
Labels: enhancement

#641 Add TestFlight link
  Demo/Info.plist
  Demo/Resources/Localizable.xcstrings
  Demo/Sources/Settings/SettingsView.swift
  Demo/Sources/Showcase/SourceCodeViewable.swift
  Demo/Xcode/Shared/Common.xcconfig
Labels: enhancement

#645 Enable new rules introduced in SwiftLint 0.53.0
  .swiftlint.yml
Labels: tooling

#644 Display SRG SSR media duration in minutes
  Demo/Sources/Model/MediaDescription.swift
Labels: enhancement

#646 Remove useless imports
  Sources/Player/Interfaces/PictureInPictureDelegate.swift
  Sources/Player/MediaSelection/AudibleMediaSelector.swift
  Sources/Player/PictureInPicture/CustomPictureInPicture.swift
  Sources/Player/PictureInPicture/PictureInPicture.swift
  Sources/Player/PictureInPicture/SystemPictureInPicture.swift
  Sources/Player/Player+ItemUpdate.swift
  Tests/AnalyticsTests/ComScore/ComScoreTrackerRateTests.swift
Labels: enhancement

#652 Fix methods incorrectly marked as deprecated in documentation catalogs
  Sources/Player/UserInterface/LayoutReader.swift
  Sources/Player/UserInterface/Slider.swift
  Sources/Player/UserInterface/VisibilityTracker.swift
Labels: enhancement

#655 Improve page titles
  Sources/Player/Player.docc/ControlCenter.md
  Sources/Player/Player.docc/FairPlayStreaming.md
  Sources/Player/Player.docc/MediaSelection.md
  Sources/Player/Player.docc/PictureInPicture.md
  Sources/Player/Player.docc/Player.md
  Sources/Player/Player.docc/ProgressTracking.md
  Sources/Player/Player.docc/ResourceLoading.md
  Sources/Player/Player.docc/SettingsMenu.md
  Sources/Player/Player.docc/UserInterface.md
Labels: documentation

#659 Update markdownlint
  .markdownlint.yaml
  Gemfile
  Gemfile.lock
  Makefile
  Scripts/check-quality.sh
  Sources/Player/Player.docc/PictureInPicture.md
  Sources/Player/Player.docc/Tracking.md
  docs/CONTINUOUS_INTEGRATION.md
  docs/DEVELOPMENT_SETUP.md
  docs/README.md
  docs/STREAM_PACKAGING_ADVICE.md
  markdown_style.rb
Labels: tooling

#662 Document asset loading
  Sources/Player/Player.docc/FairPlayStreaming.md
  Sources/Player/Player.docc/Playback.md
  Sources/Player/Player.docc/Player.md
  Sources/Player/Player.docc/ResourceLoading.md
  Sources/Player/Player.docc/Resources/fairplay@2x.jpg
  Sources/Player/Player.docc/Resources/pipes@2x.jpg
  Sources/Player/Player.docc/Resources/resource-loading@2x.jpg
Labels: documentation

#660 Improve playback documentation
  Sources/CoreBusiness/CoreBusiness.docc/CoreBusiness.md
  Sources/Player/Asset.swift
  Sources/Player/Player+PlaybackSpeed.swift
  Sources/Player/Player.docc/Playback.md
  Sources/Player/PlayerItem.swift
Labels: documentation

#664 Fix flaky test
  Tests/PlayerTests/QueuePlayer/QueuePlayerItemsTests.swift
Labels: enhancement

#665 Add asset and player item documentation extensions
  Sources/Player/Interfaces/AssetMetadata.swift
  Sources/Player/Player.docc/Asset.md
  Sources/Player/Player.docc/PlayerItem.md
  Sources/Player/PlayerItem.swift
Labels: documentation

#668 Organize progress tracker APIs
  Sources/Player/Player.docc/Extensions/Asset.md
  Sources/Player/Player.docc/Extensions/PlayerItem.md
  Sources/Player/Player.docc/Extensions/ProgressTracker.md
Labels: documentation

#669 Extract project setup to a dedicated tutorial
  Sources/Player/Player.docc/Resources/adding-package-dependency@2x.jpg
  Sources/Player/Player.docc/Tutorials/CreatingBasicUserInterface.tutorial
  Sources/Player/Player.docc/Tutorials/CreatingProjectWithPlayerDependency.tutorial
  Sources/Player/Player.docc/Tutorials/TOC/BuildingCustomUserInterfaces.tutorial
  Sources/Player/Player.docc/Tutorials/TrackingProgress.tutorial
Labels: documentation

#671 Add visibility tracking documentation and tutorial
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Tutorials/VisibilityTrackerTutorial~ios.swift
  Sources/Player/Player.docc/Extensions/ProgressTracker.md
  Sources/Player/Player.docc/Extensions/VisibilityTracker.md
  Sources/Player/Player.docc/Resources/Sources/visibility-tracker-tutorial-1.swift
  Sources/Player/Player.docc/Resources/Sources/visibility-tracker-tutorial-2.swift
  Sources/Player/Player.docc/Resources/Sources/visibility-tracker-tutorial-3.swift
  Sources/Player/Player.docc/Resources/Sources/visibility-tracker-tutorial-4.swift
  Sources/Player/Player.docc/Resources/Sources/visibility-tracker-tutorial-5.swift
  Sources/Player/Player.docc/Resources/tutorial-visibility-tracker-result@2x.png
  Sources/Player/Player.docc/Resources/tutorial-visibility-tracker-result~dark@2x.png
  Sources/Player/Player.docc/Resources/tutorial-visibility-tracker@2x.png
  Sources/Player/Player.docc/Resources/tutorial-visibility-tracker@2x~dark@2x.png
  Sources/Player/Player.docc/Resources/visibility-tracking@2x.jpg
  Sources/Player/Player.docc/Tutorials/TrackingVisibility.tutorial
  Sources/Player/UserInterface/ProgressTracker.swift
  Sources/Player/UserInterface/VisibilityTracker.swift
Labels: documentation

#672 Add a tutorial for basic backward and forward seek
  Sources/Player/Player.docc/Resources/Sources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-1.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-2.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-3.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-4.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-5.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-6.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-1.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-2.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-3.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-4.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-5.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-6.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-tutorial/basic-ui-tutorial-3.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-tutorial/basic-ui-tutorial-4.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-tutorial/basic-ui-tutorial-6.swift
  Sources/Player/Player.docc/Resources/Sources/basic-ui-tutorial/basic-ui-tutorial-7.swift
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-1.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-1~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-2.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-2~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-3.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-3~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-4.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-4~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-5.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-5~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-6.jpg
  Sources/Player/Player.docc/Resources/basic-ui-play-pause-tutorial/basic-ui-play-pause-tutorial-6~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-1.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-1~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-2.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-2~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-3.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-3~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-4.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-4~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-5.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-5~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-6.jpg
  Sources/Player/Player.docc/Resources/basic-ui-seek-tutorial/basic-ui-seek-tutorial-6~dark.jpg
  Sources/Player/Player.docc/Resources/basic-ui-tutorial/basic-ui-tutorial-6.jpg
  Sources/Player/Player.docc/Resources/basic-ui-tutorial/basic-ui-tutorial-6~dark.jpg
  Sources/Player/Player.docc/Tutorials/CreatingBasicUserInterface.tutorial
Labels: documentation

#673 Add pinch to zoom tutorial
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Tutorials/PinchToZoomTutorial~ios.swift
  Sources/Player/Player.docc/Resources/Sources/pinch-to-zoom-tutorial/pinch-to-zoom-tutorial-1.swift
  Sources/Player/Player.docc/Resources/Sources/pinch-to-zoom-tutorial/pinch-to-zoom-tutorial-2.swift
  Sources/Player/Player.docc/Resources/Sources/pinch-to-zoom-tutorial/pinch-to-zoom-tutorial-3.swift
  Sources/Player/Player.docc/Resources/Sources/pinch-to-zoom-tutorial/pinch-to-zoom-tutorial-4.swift
  Sources/Player/Player.docc/Resources/Sources/pinch-to-zoom-tutorial/pinch-to-zoom-tutorial-5.swift
  Sources/Player/Player.docc/Resources/Sources/pinch-to-zoom-tutorial/pinch-to-zoom-tutorial-6.swift
  Sources/Player/Player.docc/Resources/Sources/progress-tracker-tutorial/progress-tracker-tutorial-1.swift
  Sources/Player/Player.docc/Resources/Sources/progress-tracker-tutorial/progress-tracker-tutorial-2.swift
  Sources/Player/Player.docc/Resources/Sources/progress-tracker-tutorial/progress-tracker-tutorial-3.swift
  Sources/Player/Player.docc/Resources/Sources/progress-tracker-tutorial/progress-tracker-tutorial-4.swift
  Sources/Player/Player.docc/Resources/Sources/progress-tracker-tutorial/progress-tracker-tutorial-5.swift
  Sources/Player/Player.docc/Resources/pinch-to-zoom-tutorial/pinch-to-zoom-tutorial-1@2x.jpg
  Sources/Player/Player.docc/Resources/pinch-to-zoom-tutorial/pinch-to-zoom-tutorial-1~dark@2x.jpg
  Sources/Player/Player.docc/Resources/pinch-to-zoom-tutorial/pinch-to-zoom-tutorial-3@2x.jpg
  Sources/Player/Player.docc/Resources/pinch-to-zoom-tutorial/pinch-to-zoom-tutorial-3~dark@2x.jpg
  Sources/Player/Player.docc/Resources/pinch-to-zoom@2x.jpg
  Sources/Player/Player.docc/Tutorials/DetectingFullScreen.tutorial
  Sources/Player/Player.docc/Tutorials/SupportingPinchToZoom.tutorial
  Sources/Player/Player.docc/Tutorials/TOC/BuildingCustomUserInterfaces.tutorial
  Sources/Player/Player.docc/UserInterface.md
  Sources/Player/UserInterface/LayoutReader.swift
Labels: documentation
