Repository SRGSSR/pillarbox-apple, pull requests merged in 2023-12, with the labels that each got.

#675 Add tutorial artworks
  Sources/Player/Player.docc/Outlines/building-custom-user-interfaces/building-custom-user-interfaces-1.jpg
  Sources/Player/Player.docc/Outlines/building-custom-user-interfaces/building-custom-user-interfaces-2.jpg
  Sources/Player/Player.docc/Outlines/building-custom-user-interfaces/building-custom-user-interfaces-3.jpg
  Sources/Player/Player.docc/Outlines/building-custom-user-interfaces/building-custom-user-interfaces.tutorial
Labels: documentation

#678 Remove test streams
  Demo/Packages/youtube-identifier/.swiftpm/xcode/xcshareddata/xcschemes/YouTubeIdentifier-Package.xcscheme
  Demo/Packages/youtube-identifier/Package.swift
  Demo/Packages/youtube-identifier/Sources/YouTubeIdentifier/YouTubeIdentifier.swift
  Demo/Packages/youtube-identifier/Tests/YouTubeIdentifierTests/YouTubeIdentifierTests.swift
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Pillarbox-demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Demo/Sources/Examples/ExamplesView.swift
  Demo/Sources/Model/Media.swift
  Demo/Sources/Model/Template.swift
  Demo/Sources/YouTube/PlayerItem.swift
  Demo/Sources/YouTube/YouTubeError.swift
  Demo/Sources/YouTube/YouTubeMetadata.swift
  Plugins/PackageInfoPlugin/plugin.swift
  docs/README.md
  docs/TEST_STREAMS.md
Labels: enhancement

#679 Add AirPlay tutorial
  Sources/Player/Player.docc/Articles/airplay/airplay-card.jpg
  Sources/Player/Player.docc/Articles/airplay/airplay-card.png
  Sources/Player/Player.docc/Articles/airplay/airplay.md
  Sources/Player/Player.docc/Tutorials/supporting-airplay.tutorial
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-1-1.swift
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-1.jpg
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-1.swift
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-1~dark.jpg
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-2.jpg
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-2.swift
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-2~dark.jpg
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-3.jpg
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-3.swift
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-3~dark.jpg
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-4.jpg
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay-2-4~dark.jpg
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay.tutorial
Labels: documentation

#680 Media selection documentation
  Sources/Player/Player.docc/Articles/media-selection.md
  Sources/Player/Player.docc/Articles/player/player.md
  Sources/Player/Player.docc/Articles/selecting-subtitles-and-alternative-audio-tracks.md
  Sources/Player/Player.docc/Articles/stream-packaging-advice.md
  docs/README.md
  docs/STREAM_PACKAGING_ADVICE.md
Labels: documentation

#682 Move readme to the root directory
  README.md
Labels: documentation

#683 Make the version script more tolerant for build by Swift Package Index
  Artifacts/PackageInfo.artifactbundle/package-info.sh
Labels: tooling

#681 Document playback speed support
  Sources/Player/Player.docc/Articles/playback-speed.md
  Sources/Player/Player.docc/Articles/playback/playback.md
  Sources/Player/Player.docc/Articles/player/player.md
  Sources/Player/Player.docc/Articles/settings-menu.md
  Sources/Player/Player.docc/Articles/stream-packaging-advice.md
  Sources/Player/Player.docc/Articles/subtitles-and-alternative-audio-tracks.md
Labels: documentation

#684 Integrate with Swift Package Index
  .spi.yml
  README.md
Labels: documentation

#685 Add tracking documentation
  Sources/Player/Player.docc/Articles/tracking/tracking.md
  Sources/Player/Tracking/PlayerItemTracker.swift
Labels: documentation

#688 Reoganize Player documention
  Sources/Player/Player.docc/Extensions/player-object.md
Labels: documentation

#689 Document analytics integration
  Demo/Sources/Application/AppDelegate.swift
  Sources/Analytics/Analytics.docc/Analytics.md
  Sources/Analytics/Analytics.docc/Events.md
  Sources/Analytics/Analytics.docc/PageViews.md
  Sources/Analytics/Analytics.docc/Streaming.md
  Sources/Analytics/Analytics.docc/analytics.md
  Sources/Analytics/Analytics.docc/events.md
  Sources/Analytics/Analytics.docc/page-views.md
  Sources/Analytics/Analytics.docc/setup.md
  Sources/Analytics/Analytics.docc/user-consent.md
  Sources/Analytics/Analytics.docc/web-content-tracking.md
  Sources/Analytics/Analytics.swift
  Sources/Analytics/UserInterface/ContainerPageViewTracking.swift
  Sources/Analytics/UserInterface/PageViewTracking.swift
  Sources/CoreBusiness/CoreBusiness.docc/CoreBusiness.md
  Tests/AnalyticsTests/TestCase.swift
Labels: documentation

#690 Polish documentation
  Sources/Player/Player+Items.swift
  Sources/Player/Player+Navigation.swift
  Sources/Player/Player.docc/Articles/player/player.md
  Sources/Player/Player.docc/Articles/playlists.md
  Sources/Player/Player.docc/Outlines/integrating-with-system-features/integrating-with-system-features-1.jpg
  Sources/Player/Player.docc/Outlines/integrating-with-system-features/integrating-with-system-features-2.jpg
  Sources/Player/Player.docc/Outlines/integrating-with-system-features/integrating-with-system-features-3.jpg
  Sources/Player/Player.docc/Outlines/integrating-with-system-features/integrating-with-system-features.tutorial
  Sources/Player/Player.docc/Tutorials/enabling-in-app-picture-in-picture.tutorial
  Sources/Player/Player.swift
Labels: documentation

#695 Update cells appearance for tvOS
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Sources/ContentLists/ContentListView.swift
  Demo/Sources/ContentLists/ContentListsView.swift
  Demo/Sources/Examples/ExamplesView.swift
  Demo/Sources/Search/SearchView.swift
  Demo/Sources/Settings/SettingsView.swift
  Demo/Sources/Showcase/ShowcaseView.swift
  Demo/Sources/Views/Cell.swift
  Demo/Sources/Views/CustomList.swift
  Demo/Sources/Views/CustomSection.swift
Labels: enhancement

#699 Enhance cells appearance for tvOS
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Sources/ContentLists/ContentListView.swift
  Demo/Sources/ContentLists/ContentListsView.swift
  Demo/Sources/Examples/ExamplesView.swift
  Demo/Sources/Examples/ExamplesViewModel.swift
  Demo/Sources/Model/Media.swift
  Demo/Sources/Model/MediaDescription.swift
  Demo/Sources/Search/SearchView.swift
  Demo/Sources/Settings/SettingsView.swift
  Demo/Sources/Showcase/ShowcaseView.swift
  Demo/Sources/Views/Cell.swift
  Demo/Sources/Views/CustomList.swift
  Demo/Sources/Views/CustomNavigationLink.swift
  Demo/Sources/Views/CustomSection.swift
  Demo/Sources/Views/MediaCardView.swift
  Demo/Sources/Views/MessageViews.swift
  Demo/Sources/Views/View.swift
Labels: enhancement

#701 Improve the display of examples on tvOS
  Demo/Sources/Model/Media.swift
  Demo/Sources/Model/Template.swift
Labels: enhancement

#706 Document SwiftUI property wrapper usage recommendations
  Sources/Player/Player.docc/Articles/state-observation/state-observation.md
Labels: documentation
