Repository SRGSSR/pillarbox-apple, pull requests merged in 2024-05, with the labels that each got.

#856 Improved tvOS playlist experience
  Demo/Sources/Showcase/Playlist/PlaylistView.swift
  Sources/Player/Extensions/AVPlayerItem.swift
Labels: enhancement

#857 Add demo privacy manifest
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Resources/PrivacyInfo.xcprivacy
Labels: enhancement

#858 Fix documentation link
  README.md
Labels: documentation

#865 Add blocked time range URN example
  Demo/Sources/Examples/ExamplesViewModel.swift
  Demo/Sources/Model/Template.swift
Labels: enhancement

#866 Display artwork image for audio
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Views/View.swift
Labels: enhancement

#868 Add a test for nested time range
  Tests/PlayerTests/Player/BlockedTimeRangeTests.swift
Labels: enhancement

#869 Use new API for localization
  Sources/CoreBusiness/DataProvider/Errors.swift
  Sources/CoreBusiness/Extensions/HTTPURLResponse.swift
  Sources/CoreBusiness/Model/MediaComposition+BlockingReason.swift
  Sources/Player/MediaSelection/MediaSelectionOption.swift
  Sources/Player/UserInterface/AVPlayerViewControllerSpeedCoordinator.swift
Labels: enhancement

#870 Add HLS documentation links
  Sources/CoreBusiness/DataProvider/Server.swift
  Sources/Player/Player.docc/Articles/stream-packaging-advice.md
Labels: documentation

#872 Apply current demo settings to player instances
  Demo/Sources/Players/PlayerConfiguration.swift
Labels: bug

#874 Prevent controls from being toggled while interacting
  Demo/Sources/Players/PlaybackView.swift
Labels: enhancement

#877 Fix Control Center integration documentation on tvOS
  Sources/Player/Player.docc/Articles/control-center/control-center.md
Labels: documentation

#881 Fix undesired animation
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Tools/Constant.swift
Labels: bug

#883 Avoid settings menu being closed when controls disappear
  Demo/Sources/Players/PlaybackView.swift
Labels: bug

#889 Add Swift Package Index documentation links
  .spi.yml
  README.md
Labels: documentation

#891 Improve server support in Core Business
  Demo/Sources/Application/AppDelegate.swift
  Demo/Sources/ContentLists/ContentListView.swift
  Demo/Sources/ContentLists/ContentListsView.swift
  Demo/Sources/Examples/ExamplesView.swift
  Demo/Sources/Model/Media.swift
  Demo/Sources/Model/ServerSetting.swift
  Demo/Sources/Settings/UserDefaults.swift
  Sources/CoreBusiness/DataProvider/DataProvider.swift
  Sources/CoreBusiness/DataProvider/Server.swift
  Sources/CoreBusiness/Model/ImageWidth.swift
  Sources/CoreBusiness/Model/MediaMetadata.swift
Labels: enhancement

#893 Add playback HUD support
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Resources/Localizable.xcstrings
  Demo/Sources/Application/AppDelegate.swift
  Demo/Sources/ContentLists/ContentListView.swift
  Demo/Sources/ContentLists/ContentListsView.swift
  Demo/Sources/Model/PlaybackHudColor.swift
  Demo/Sources/Model/PlaybackHudFontSize.swift
  Demo/Sources/Model/SeekBehaviorSetting.swift
  Demo/Sources/Players/SimplePlayerView.swift
  Demo/Sources/Settings/SettingsView.swift
  Demo/Sources/Settings/UserDefaults.swift
Labels: enhancement

#895 Immediately dismiss the keyboard when scrolling
  Demo/Sources/Examples/ExamplesView.swift
  Demo/Sources/Settings/SettingsView.swift
Labels: bug

#896 Update Xcode to version 15.4
  .xcode-version
Labels: tooling

#894 Provide audio description information in analytics labels
  Sources/Analytics/CommandersAct/CommandersActTracker.swift
Labels: enhancement
