Repository SRGSSR/pillarbox-apple, pull requests merged in 2024-10, with the labels that each got.

#1024 Document known AirPlay issue with iPad apps run on macOS
  docs/KNOWN_ISSUES.md
Labels: documentation

#1027 Handle the list selection when the current player item changes
  Sources/Player/UserInterface/Playlist.swift
Labels: bug

#1029 Update dependencies, including comScore and Commanders Act SDKs
  Demo/Pillarbox-demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
Labels: enhancement

#1039 Fix Picture in Picture button documentation
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Showcase/PiP/TransitionPiPView.swift
  Sources/Player/UserInterface/PictureInPictureButton.swift
Labels: enhancement

#1043 Set LSMinimumSystemVersion to 14.0
  Demo/Info.plist
Labels: enhancement

#981 Deliver metadata with business errors
  Sources/CoreBusiness/DataProvider/DataProvider.swift
  Sources/CoreBusiness/Extensions/PlayerItem.swift
  Sources/CoreBusiness/Model/MediaMetadata.swift
  Sources/Player/Asset.swift
  Tests/CoreBusinessTests/DataProviderTests.swift
Labels: enhancement

#1050 Update fastlane to version 2.225.0
  Gemfile.lock
Labels: tooling
