Repository SRGSSR/pillarbox-apple, pull requests merged in 2024-01, with the labels that each got.

#709 Update dependencies to most recent versions
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Pillarbox-demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
  Sources/Circumspect/Matchers.swift
  Sources/Circumspect/Similarity.swift
  Tests/PlayerTests/Tools/Matchers.swift
Labels: enhancement

#711 Add an access to Pillarbox Web via a WebView
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Resources/Settings.bundle/Root.plist
  Demo/Sources/Router/RouterDestination.swift
  Demo/Sources/Settings/SettingsBundle.swift
  Demo/Sources/Showcase/ShowcaseView.swift
  Demo/Sources/Views/WebView~ios.swift
Labels: enhancement

#713 Animate video view display
  Demo/Sources/Players/PlaybackView.swift
Labels: enhancement

#715 Update Xcode version used for CI to to 15.2
  .xcode-version
  fastlane/Fastfile
Labels: tooling

#719 Fix product name conflicts
  .github/PULL_REQUEST_TEMPLATE.md
  .swiftpm/xcode/xcshareddata/xcschemes/Pillarbox-NoDebug.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/Pillarbox.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/PillarboxAnalytics.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/PillarboxCircumspect.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/PillarboxCore.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/PillarboxCoreBusiness.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/PillarboxPlayer.xcscheme
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Pillarbox.playground/Contents.swift
  Demo/Pillarbox.playground/contents.xcplayground
  Demo/Pillarbox.playground/playground.xcworkspace/contents.xcworkspacedata
  Makefile
  Package.resolved
  Package.swift
  Sources/Player/Player+SkipToDefault.swift
  Sources/Player/Player.docc/Tutorials/creating-project/creating-project-2-1.png
  Sources/Player/Player.docc/Tutorials/creating-project/creating-project-2-1~dark.png
  Sources/Player/Player.docc/Tutorials/creating-project/creating-project-2-2.png
  Sources/Player/Player.docc/Tutorials/creating-project/creating-project-2-2~dark.png
  Sources/Player/Player.docc/Tutorials/creating-project/creating-project.tutorial
  docs/DEVELOPMENT_SETUP.md
  fastlane/Fastfile
Labels: enhancement

#720 Make player animations smoother
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Players/SimplePlayerView.swift
  Demo/Sources/Showcase/Multi/SingleView.swift
  README.md
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-1-6.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-1.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-2.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-3.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-4.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-5.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-6.swift
Labels: enhancement

#721 Revise some documentation images
  Sources/Player/Player.docc/Articles/airplay/airplay-card.jpg
  Sources/Player/Player.docc/Articles/control-center/control-center-card.jpg
  Sources/Player/Player.docc/Articles/fairplay-streaming/fairplay-streaming-card.jpg
  Sources/Player/Player.docc/Articles/picture-in-picture/picture-in-picture-card.jpg
  Sources/Player/Player.docc/Articles/playback/playback-card.jpg
  Sources/Player/Player.docc/Articles/resource-loading/resource-loading-card.jpg
  Sources/Player/Player.docc/Articles/state-observation/state-observation-card.jpg
  Sources/Player/Player.docc/Articles/tracking/tracking-card.jpg
  Sources/Player/Player.docc/Tutorials/integrating-with-control-center/integrating-with-control-center.jpg
  Sources/Player/Player.docc/Tutorials/supporting-airplay/supporting-airplay.jpg
  Sources/Player/Player.docc/Tutorials/supporting-basic-picture-in-picture/supporting-basic-picture-in-picture.jpg
Labels: documentation

#722 Create a computed property to detect non-zero playback rates
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Players/SimplePlayerView.swift
  Demo/Sources/Showcase/Multi/SingleView.swift
  Demo/Tutorials/TrackingVisibilityTutorial~ios.swift
  README.md
  Sources/Player/Player+Playback.swift
  Sources/Player/Player.docc/Articles/state-observation/state-observation.md
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-1-6.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-1.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-2.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-3.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-4.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-5.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-6.swift
  Sources/Player/Player.docc/Tutorials/tracking-visibility/tracking-visibility-1-1.swift
  Sources/Player/Player.docc/Tutorials/tracking-visibility/tracking-visibility-1-2.swift
  Sources/Player/Player.docc/Tutorials/tracking-visibility/tracking-visibility-1-3.swift
  Sources/Player/Player.docc/Tutorials/tracking-visibility/tracking-visibility-1-4.swift
  Sources/Player/Player.docc/Tutorials/tracking-visibility/tracking-visibility-1-5.swift
  Sources/Player/Player.swift
Labels: enhancement

#723 Remove superfluous selves
  Demo/Sources/ContentLists/ContentListsView.swift
Labels: enhancement

#726 Eliminate undesired layer animations
  Sources/Player/UserInterface/VideoLayerView.swift
Labels: bug

#727 Extend layout past the safe area
  Demo/Sources/Players/StartAtGivenTimeView.swift
Labels: bug

#732 Rename isRunning as shouldPlay
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Players/SimplePlayerView.swift
  Demo/Sources/Showcase/Multi/SingleView.swift
  Demo/Tutorials/TrackingVisibilityTutorial~ios.swift
  README.md
  Sources/Core/BodyCounter.swift
  Sources/Player/Player+Playback.swift
  Sources/Player/Player.docc/Articles/state-observation/state-observation.md
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-1-6.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-1.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-2.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-3.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-4.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-5.swift
  Sources/Player/Player.docc/Tutorials/creating-basic-user-interface/creating-basic-user-interface-2-6.swift
  Sources/Player/Player.docc/Tutorials/tracking-visibility/tracking-visibility-1-1.swift
  Sources/Player/Player.docc/Tutorials/tracking-visibility/tracking-visibility-1-2.swift
  Sources/Player/Player.docc/Tutorials/tracking-visibility/tracking-visibility-1-3.swift
  Sources/Player/Player.docc/Tutorials/tracking-visibility/tracking-visibility-1-4.swift
  Sources/Player/Player.docc/Tutorials/tracking-visibility/tracking-visibility-1-5.swift
  Sources/Player/Player.swift
Labels: enhancement

#731 Make all skips consistently non-smooth
  Sources/Player/Player+SkipToDefault.swift
Labels: enhancement

#734 Fix replay behavior with unconsumed failed items
  Demo/Sources/Examples/ExamplesViewModel.swift
  Demo/Sources/Model/Template.swift
  Sources/Player/Player+Replay.swift
  Sources/Streams/Stream.swift
  Tests/PlayerTests/Player/ReplayChecksTests.swift
Labels: bug

#733 Update start time example for consistency with other platforms
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Sources/Model/Media.swift
  Demo/Sources/Players/StartAtGivenTimeView.swift
  Demo/Sources/Router/RouterDestination.swift
  Demo/Sources/Showcase/ShowcaseView.swift
  Sources/Player/Extensions/AVPlayerItem.swift
  Sources/Player/Types/Position.swift
Labels: enhancement

#737 Avoid sending several page views to the analytics
  Demo/Sources/ContentLists/ContentListsView.swift
  Demo/Sources/Examples/ExamplesView.swift
  Demo/Sources/Settings/SettingsView.swift
  Demo/Sources/Showcase/ShowcaseView.swift
  Demo/Sources/Views/CustomList.swift
Labels: bug

#742 Fix pre-commit hook
  Scripts/check-quality.sh
Labels: tooling

#740 Document how to trust plugins in a continuous integration setup
  README.md
Labels: documentation

#744 Fix comScore test flakiness
  Gemfile.lock
  Tests/AnalyticsTests/ComScore/ComScoreTrackerTests.swift
Labels: enhancement

#746 Increase playback speed during a long press gesture
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Resources/Localizable.xcstrings
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Views/HighSpeedView~ios.swift
Labels: enhancement

#755 Update data provider to version 19.0.0
  Demo/Pillarbox-demo.xcodeproj/project.pbxproj
  Demo/Pillarbox-demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: enhancement
