Repository SRGSSR/pillarbox-apple, pull requests merged in 2025-04, with the labels that each got.

#1182 Add tracker for multi-tap skip gesture implementation
  Demo/Resources/Localizable.xcstrings
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Views/VerticalLabelStyle.swift
  Sources/Player/Player+Skip.swift
  Sources/Player/Player.docc/Articles/playback-speed-article.md
  Sources/Player/Player.docc/Articles/subtitles-and-alternative-audio-tracks-article.md
  Sources/Player/Player.docc/Extensions/player-extension.md
  Sources/Player/Player.docc/Outlines/building-custom-user-interfaces/building-custom-user-interfaces.tutorial
  Sources/Player/Player.docc/PillarboxPlayer.md
  Sources/Player/Player.docc/Tutorials/supporting-pinch-to-zoom/supporting-pinch-to-zoom-2-3.swift
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures-1-1.jpg
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures-1-1.swift
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures-1-1~dark.jpg
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures-1-2.swift
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures-1-3.swift
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures-2-1.swift
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures-2-2.jpg
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures-2-2.swift
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures-2-2~dark.jpg
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures-intro.jpg
  Sources/Player/Player.docc/Tutorials/supporting-skip-gestures/supporting-skip-gestures.tutorial
  Sources/Player/PlayerConfiguration.swift
  Sources/Player/Types/Skip.swift
  Sources/Player/UserInterface/SkipTracker.swift
  Sources/Player/UserInterface/VisibilityTracker.swift
  Tests/PlayerTests/UserInterface/SkipTrackerTests.swift
Labels: enhancement

#1192 Fix toggle gesture
  Demo/Sources/Players/PlaybackView.swift
Labels: enhancement

#1193 Update macOS and Xcode versions
  .github/workflows/ci.yml
  .github/workflows/nightlies.yml
  .github/workflows/releases.yml
  .xcode-version
  Tests/PlayerTests/Player/QueueTests.swift
Labels: enhancement

#1195 Dependency update
  Demo/Pillarbox-demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
Labels: enhancement

#1196 Update gems
  Gemfile.lock
Labels: tooling

#1197 Disable skip gestures on iOS 17
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Views/View.swift
Labels: bug

#1199 Fix settings preview
  Demo/Sources/Settings/SettingsView.swift
Labels: bug

#1200 Allow to start Picture-in-Picture automatically for inline contents
  Sources/Player/PictureInPicture/CustomPictureInPicture.swift
  Sources/Player/PictureInPicture/SystemPictureInPicture.swift
Labels: enhancement

#1201 Fix preprocessor condition
  Sources/Player/PictureInPicture/CustomPictureInPicture.swift
Labels: bug

#1204 Improve demo slider
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Views/HSlider.swift
Labels: enhancement
