Repository SRGSSR/pillarbox-apple, pull requests merged in 2025-06, with the labels that each got.

#1238 Improve CC-related recommendations
  Sources/Player/Player.docc/Articles/stream-encoding-and-packaging-advice-article/stream-encoding-and-packaging-advice-article.md
Labels: documentation

#1242 Ignore Difference package updates
  .github/dependabot.yml
Labels: tooling

#1247 Avoid blurry images for skip buttons
  Demo/Sources/Extensions/Image.swift
  Demo/Sources/Players/PlaybackView.swift
Labels: bug, enhancement
