Repository SRGSSR/pillarbox-apple, pull requests merged in 2025-02, with the labels that each got.

#1131 Fix slider background and animations
  Demo/Sources/Players/PlaybackView.swift
Labels: bug

#1132 Update dependencies
  Demo/Pillarbox-demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: enhancement

#1130 Replace futures with async publisher
  Demo/Sources/Application/DemoApp.swift
  Demo/Sources/Extensions/URL.swift
  Demo/Sources/Players/VanillaPlayerView.swift
  Package.swift
  Plugins/PackageInfoPlugin/plugin.swift
  Sources/Core/AsyncPublisher.swift
  Sources/Core/ReplaySubject.swift
  Sources/Core/ReplaySubscription.swift
  Sources/Player/Publishers/AVAssetPublishers.swift
  Sources/Player/Publishers/AVAsynchronousKeyValueLoadingPublishers.swift
  Sources/Player/Publishers/BoundaryTimePublisher.swift
  Sources/Player/Publishers/BoundaryTimeSubscription.swift
  Sources/Player/Publishers/PeriodicTimePublisher.swift
  Sources/Player/Publishers/PeriodicTimeSubscription.swift
  Tests/CoreTests/AsyncPublisherTests.swift
Labels: enhancement

#1133 Remove custom server initializer
  Demo/Resources/Localizable.xcstrings
  Demo/Sources/ContentLists/ContentListView.swift
  Demo/Sources/ContentLists/ContentListsView.swift
  Demo/Sources/Examples/ExamplesView.swift
  Demo/Sources/Model/Media.swift
  Demo/Sources/Model/ServerSetting.swift
  Demo/Sources/Settings/UserDefaults.swift
  Sources/CoreBusiness/DataProvider/Server.swift
Labels: bug, enhancement

#1136 Refactor Server from struct to enum
  Sources/CoreBusiness/DataProvider/Server.swift
Labels: enhancement

#1141 Avoid code signing when checking that the demo compiles
  .github/workflows/ci.yml
  Makefile
  Scripts/public/build-demo.sh
  fastlane/Fastfile
Labels: tooling

#1144 Improve missing doc detection
  .swiftlint.yml
  Demo/Sources/Extensions/URL.swift
  Sources/Analytics/AnalyticsDelegate.swift
  Sources/Analytics/ComScore/Capture/ComScoreHit.swift
  Sources/Analytics/ComScore/ComScoreTracker.swift
  Sources/Analytics/CommandersAct/Capture/CommandersActHit.swift
  Sources/Analytics/CommandersAct/CommandersActTracker.swift
  Sources/Analytics/UserInterface/ContainerPageViewTracking.swift
  Sources/Circumspect/Similarity.swift
  Sources/Core/AsyncPublisher.swift
  Sources/Core/ReplaySubject.swift
  Sources/CoreBusiness/Model/MediaMetadata.swift
  Sources/Monitoring/MetricsTracker.swift
  Sources/Player/Metrics/MetricEvent.swift
  Sources/Player/PictureInPicture/PictureInPicture.swift
  Sources/Player/Player.swift
  Sources/Player/PlayerItem.swift
  Sources/Player/Types/ImageSource.swift
  Sources/Player/UserInterface/LazyImage.swift
  Sources/Player/UserInterface/PictureInPictureButton.swift
  Sources/Player/UserInterface/RoutePickerView.swift
  Sources/Player/UserInterface/SystemVideoView.swift
  Sources/Player/UserInterface/VideoView.swift
  Tests/MonitoringTests/MetricPayload.swift
  Tests/PlayerTests/Tools/Similarity.swift
Labels: tooling
