Repository SRGSSR/pillarbox-apple, pull requests merged in 2025-09, with the labels that each got.

#1282 Add recommendations for the `DEFAULT` attribute
  Sources/Player/Player.docc/Articles/stream-encoding-and-packaging-advice-article/stream-encoding-and-packaging-advice-article.md
Labels: documentation

#1290 Update toolchain to Xcode, iOS and tvOS 26
  .github/workflows/ci.yml
  .github/workflows/nightlies.yml
  .github/workflows/releases.yml
  .xcode-version
  Demo/Pillarbox-demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: tooling

#1293 Add a playlist section in the playback article
  Demo/Sources/Showcase/Playlist/PlaylistView.swift
  Sources/Analytics/ComScore/ComScoreStreamingAnalytics.swift
  Sources/Analytics/CommandersAct/CommandersActTracker.swift
  Sources/Analytics/Extensions/Numeric.swift
  Sources/Monitoring/Extensions/Date.swift
  Sources/Player/Player.docc/Articles/playback/playback-article.md
  Sources/Player/Player.docc/Extensions/player-extension.md
  Sources/Player/Player/Player+ControlCenter.swift
  Sources/Player/Player/Player+ItemNavigation.swift
  Sources/Player/Player/Player+Navigation.swift
  Sources/Player/Player/Player.swift
  Sources/Player/Types/NavigationMode.swift
  Tests/PlayerTests/MediaSelection/PreferredLanguagesForMediaSelectionTests.swift
  Tests/PlayerTests/Playlist/ItemNavigationBackwardChecksTests.swift
  Tests/PlayerTests/Playlist/ItemNavigationBackwardTests.swift
  Tests/PlayerTests/Playlist/ItemNavigationForwardChecksTests.swift
  Tests/PlayerTests/Playlist/ItemNavigationForwardTests.swift
  Tests/PlayerTests/Playlist/ItemNavigationSmartBackwardChecksTests.swift
  Tests/PlayerTests/Playlist/ItemNavigationSmartBackwardTests.swift
  Tests/PlayerTests/Playlist/ItemNavigationSmartForwardChecksTests.swift
  Tests/PlayerTests/Playlist/ItemNavigationSmartForwardTests.swift
  Tests/PlayerTests/Playlist/NavigationBackwardTests.swift
  Tests/PlayerTests/Playlist/NavigationSmartBackwardChecksTests.swift
  Tests/PlayerTests/Playlist/NavigationSmartForwardChecksTests.swift
  Tests/PlayerTests/Playlist/NavigationSmartForwardTests.swift
Labels: documentation

#1296 Fix documentation
  Demo/Sources/ContentLists/ContentListView.swift
  Demo/Sources/Views/Modal.swift
  README.md
  Sources/Player/Player.docc/Articles/playback-speed-article.md
  Sources/Player/Player.docc/Articles/subtitles-and-alternative-audio-tracks-article.md
  Sources/Player/Player.docc/PillarboxPlayer.md
Labels: enhancement
