Repository SRGSSR/pillarbox-apple, pull requests merged in 2025-05, with the labels that each got.

#1206 Prefix plugin name to avoid conflicts
  Package.swift
  Sources/Player/Resources/Localizable.xcstrings
Labels: enhancement

#1207 Display current menu selections
  Demo/Sources/Players/PlaybackView.swift
  Sources/Player/Player+SettingsMenu.swift
Labels: enhancement

#1209 Remove explicit equatable conformance
  Sources/Player/Types/TimeRange.swift
Labels: enhancement

#1208 Fix player observability when empty
  Sources/Player/Player.swift
  Sources/Player/Publishers/AVPlayerItemPublishers.swift
  Sources/Player/Publishers/PlayerPublishers.swift
  Sources/Player/Publishers/QueuePlayerPublishers.swift
  Sources/Player/Tracking/Tracker.swift
  Tests/PlayerTests/Player/PlayerTests.swift
Labels: bug

#1211 Support dynamic skips symbols based on player configuration
  Demo/Resources/Localizable.xcstrings
  Demo/Sources/Extensions/Image.swift
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Players/PlayerConfiguration.swift
  Demo/Sources/Settings/SettingsView.swift
  Demo/Sources/Settings/UserDefaults.swift
  Sources/Player/Player+Skip.swift
Labels: enhancement

#1213 Fix documentation
  Sources/Player/Player.swift
Labels: documentation

#1214 Improve standard settings menu
  Demo/Resources/Localizable.xcstrings
  Demo/Sources/Examples/ExamplesView.swift
  Demo/Sources/Model/SeekBehaviorSetting.swift
  Demo/Sources/Views/CustomSection.swift
  Sources/Player/MediaSelection/MediaSelectionOption.swift
  Sources/Player/Player+SettingsMenu.swift
  Sources/Player/Resources/Localizable.xcstrings
Labels: enhancement

#1215 Avoid using isActive as published var
  Sources/Player/Player+ControlCenter.swift
  Sources/Player/Player.swift
Labels: enhancement

#1217 Remove picker label where superfluous
  Demo/Resources/Localizable.xcstrings
  Demo/Sources/ContentLists/ContentListsView.swift
  Demo/Sources/Players/PlaybackView.swift
  Demo/Sources/Showcase/Playlist/PlaylistSelectionView.swift
  Demo/Sources/Showcase/TwinsView.swift
  Sources/Player/Player+SettingsMenu.swift
Labels: enhancement

#1220 Fix slider animation glitches
  Demo/Sources/Players/PlaybackView.swift
  Scripts/private/deliver-demo.sh
  Scripts/public/build-demo.sh
  Scripts/public/test.sh
Labels: bug

#1222 Improve CI reliability
  Tests/AnalyticsTests/CommandersAct/CommandersActEventTests.swift
  Tests/AnalyticsTests/CommandersAct/CommandersActPageViewTests.swift
  Tests/CoreTests/RangeReplaceableCollectionTests.swift
  Tests/PlayerTests/AudioSession/AVAudioSessionNotificationTests.swift
  Tests/PlayerTests/QueuePlayer/QueuePlayerSeekTests.swift
  Tests/PlayerTests/UserInterface/SkipTrackerTests.swift
  Tests/PlayerTests/UserInterface/VisibilityTrackerTests.swift
Labels: tooling

#1221 Improve documentation
  Sources/Player/UserInterface/ProgressTracker.swift
Labels: documentation

#1224 Fix slider interaction issues
  Demo/Sources/Views/HSlider.swift
Labels: bug
